# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Simon Dot's Story
tagline:          'Story Telling for the soul'
description:      'Just publishing stories'
url:              http://simondot.com
baseurl:          ''

author:
  name:           'Simon Dot'
  url:            https://twitter.com/simondot

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
